### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by rodrigoargumedo** [hshackers/hshackers.github.io#1]
It seems the repo is empty and I would like to contribute to this repo. Thanks in advance.

**Comment by zachlatta** [comment]
@lablayers

## 

Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by pixelyunicorn** [comment]
What should this site be used for? A homepage with a list of meetup groups, documents, or both?

**Comment by rodrigoargumedo** [comment]
I would suggest with both meetups and documents in the site.
